### ISSUE TITLE
Compatibility with PHP 8.0 

### ISSUE THREAD

**Issue by hrach** [contributte/facebook#14]
Thank you.

**Comment by f3l1x** [comment]
Hi, facebook/graph-sdk seems obsolete. It's moved to facebookarchive (https://github.com/facebookarchive/php-graph-sdk/issues/1217).

Any thoughts how to get it on PHP 8?

**Comment by spernica** [comment]
Hi guys, possible inspiration:
https://github.com/contributte/facebook/compare/master...spernica:php8

FB SDK is outdated without any maintenance, so I used another library from theleague company (package is maintained). I needed this package on PHP 8.

**Comment by f3l1x** [comment]
👍  Keep going.

**Comment by f3l1x** [comment]
How is it going @spernica?

**Comment by BinRoq** [comment]
def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end

**Comment by BinRoq** [comment]
def fibonacci(n)
  return n if ( 0..1 ).include? n
  (fibonacci(n - 1) + fibonacci(n - 2)) #recursive calls
end

**Comment by MartinMystikJonas** [comment]
HI @f3l1x and @spernica how does it look like with php8 support? I would like to use this package to replace obsolete kdyby/facebook in our legacy code but it does not support PHP8 yet. Can I help with finishing it?

**Comment by spernica** [comment]
@MartinMystikJonas Hi, I don't work on this anymore. Feel free to finish it as you need.

**Comment by MartinMystikJonas** [comment]
@spernica Can you sum up what needs to be done to finish it? Do you use working another solution now?

**Comment by MartinMystikJonas** [comment]
@f3l1x I checked @spernica work and it seems basically finished. I just fixed few PHPStan errors. I did not find any obvious errors or unfinished things. Next week I will try to test it with real app. 

But switch from facebook/graph-sdk to theleague/oauth2-client would lead to necessary changes of API in FacebookLogin and some features (cookie auth) are not supported.

New version therefore would be significant change. I think we should write some migration guide.

Also better tests coverage would be good. Including integration test with Facebook API. For that we would need some testing facebook app. Should I create one?

**Comment by f3l1x** [comment]
Hi @MartinMystikJonas. In the meanwhile (2021) I've forked a updated original facebook/graph-sdk (https://github.com/holyfork/facebook-graph-sdk). 

I would suggest, use this fork and release a version supporting newer PHP 8-8.1. And after that try to switch to  theleague/oauth2-client library which would need more tests and testing app, as you said.

What do you think?

**Comment by MartinMystikJonas** [comment]
Well we can do it if your fork is PHP8.1 ready.

I think most of the work on switching to theleague/oauth2-client is already done by @spernica but as I said it comes with significant change in API (for example required fields from FB has to be set in config and not as parameter when calling getLoginUrl, state parameter is not supported it seems a login by cookie is not suported at all)

IMHO for future it would be better to go for theleague package which is maintained. But as short term fix we can just update to your fork.

Version with theleague package should be either new major version (1.0?) or new package (contributte/oauth2-client?) because changes and BC breaks would be significant.

**Comment by f3l1x** [comment]
There is already https://github.com/contributte/oauth2-client package. There are dependencies on theleague/*. Can you take a look and prepare a PR to contributte/oauth2-client with updates? I will update this package to forked version of acebook/graph-sdk.

**Comment by f3l1x** [comment]
v0.4.0 bumped.

https://github.com/contributte/facebook/releases/tag/v0.4.0

**Comment by MartinMystikJonas** [comment]
@f3l1x I will check https://github.com/contributte/oauth2-client and use it in our project. If there will be any issues i will prepare PR to fix them.

Switch to your fork of facebook-graph-sdk by adding only repository will break for library clients unless they specify this repository too because repository config is used only from root composer.json. I think it would be better to publish your fork on packagist under it's own name or at least notify users in docs that they have to add repository config ot their composer.json.

**Comment by f3l1x** [comment]
I am not a big fan of publishing forks to packagit. I will put it into docs. Good idea.

**Comment by MartinMystikJonas** [comment]
Maybe also suggest replacing this package with contributte/oauth2-client for newer PHP versions
