### ISSUE TITLE
Add persistent data handler for state

### ISSUE THREAD

**Issue by JZechy** [contributte/facebook#2]
In case user will log in to his facebook during process of log in to website, there is a violation causing problem `Cross-site request forgery validation failed. Required param "state" missing from persistent data.`

The solution is add this code after getRedirectLoginHelper():
```php
$helper = $this->facebookSdk->getRedirectLoginHelper();
if(isset($_GET['state'])) {
	$helper->getPersistentDataHandler()->set('state', $_GET['state']);
}
```

[Solution on StackOverflow](https://stackoverflow.com/questions/32029116/facebook-sdk-returned-an-error-cross-site-request-forgery-validation-failed-th/44153440#44153440)

**Comment by vody105** [comment]
Hi, thank you for the issue. Are you sure that there was no problem on your side? Because it works on all of my projects without problem. Even in the situation you are posting your issue about. I do not like the solution you provided in particular, because you are overriding FB CSRF default protection. Check out the comments for the answer on SO you mentioned.

FB sdk uses `PersistentDataFactory` to determine which `$persistentDataHandler` to use when none is supplied in config:
```
       if (!$handler) {
            return session_status() === PHP_SESSION_ACTIVE
                ? new FacebookSessionPersistentDataHandler()
                : new FacebookMemoryPersistentDataHandler();
        }

```
I suppose we add a new option so that we can chose which handler to choose (`memory` vs `session`) with default value `session`? The problem might be in FB calling the factory before we have session active and it creates memory handler. But I am not sure if this is it. Can @JZechy try it if adding `'persistent_data_handler' => 'session',` into `$appData` in `FacebookExtension` solves your issue? Thank you.  @f3l1x What do you think?

**Comment by f3l1x** [comment]
Well, I don't get it, we are running this package in many applications and no error appears. Could you please elaborate more? @JZechy

**Comment by JZechy** [comment]
@f3l1x Can't get nothing more, on local it even works everytime. But on test server, when I try to login as test user in incognito window, I always get stucked on this error.

The local and test server are even the same machines, and same configuration. Only difference is debug mode on local.

**Comment by f3l1x** [comment]
Hmm, what about ensure that sessions is started.

```
services:
  facebook.xyz: 
    setup:
       - ensureSession()
```

It could force `session->start()`.

**Comment by JZechy** [comment]
Well, I got new knowledge about this. When Facebook redirect you back to your site, where you are processing facebook response and refresh this page (got one without redirect), it results in mentioned error. 

Bud I don't understand why there is then this error if the user log in to his facebook during login process, after facebook send him back, he is immediately after processing redirected to homepage.

**Comment by vody105** [comment]
@JZechy Try what I pushed today.

**Comment by JZechy** [comment]
Hi,
sorry for long wait... In time of sending this issue i rewrite login to Facebook SDK, but that error is still there, even with my workaround, so maybe there is some error in my integration.

**Comment by kientv** [comment]
> 'persistent_data_handler' => 'session'

@vody105  You are right, thanks.
This is my code:

```
$fb = new Facebook([
            'app_id' => config('app.facebook_app_id'),
            'app_secret' => config('app.facebook_app_secret'),
            'default_graph_version' => 'v20.0',
            'persistent_data_handler' => 'session',
            'persistent_data_handler' => new FacebookPersistentDataHandler(),
]);
```

```
class FacebookPersistentDataHandler implements \Facebook\PersistentData\PersistentDataInterface {
    public function get($key) {
      return \Session::get('facebook.' . $key);
    }

    public function set($key, $value) {
      \Session::put('facebook.' . $key, $value);
    }
}
```
But i see new error:
`(ErrorException(code: 0): Undefined array key 1 at /vendor/facebook/graph-sdk/src/Facebook/Http/GraphRawResponse.php:108)`
